from __future__ import annotations

import argparse
import html
import json
import os
import posixpath
import re
import unicodedata
import zipfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.parse import unquote, urlparse
import xml.etree.ElementTree as ET


ATOM_NS = "http://www.w3.org/2005/Atom"
BLOGGER_NS = "http://schemas.google.com/blogger/2018"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}
GENERATED = "<!-- generated by tools/import_blogger_takeout.py -->"
SITE_ORIGIN = "https://blog.eesjv.com.br"
SITE_DESCRIPTION = "Site institucional da Escola Estadual São José, em Vicentina/MS."
SOCIAL_IMAGE_URL = f"{SITE_ORIGIN}/assets/img/sobre/escola.jpeg"
WEEKDAYS = [
    "segunda-feira",
    "terça-feira",
    "quarta-feira",
    "quinta-feira",
    "sexta-feira",
    "sábado",
    "domingo",
]
MONTHS = [
    "janeiro",
    "fevereiro",
    "março",
    "abril",
    "maio",
    "junho",
    "julho",
    "agosto",
    "setembro",
    "outubro",
    "novembro",
    "dezembro",
]


@dataclass
class Post:
    title: str
    slug: str
    published: datetime
    date_label: str
    author: str
    excerpt: str
    content: str
    cover: str | None
    labels: list[str]
    post_path: str
    generated_title: bool
    instagram_url: str | None


@dataclass
class Event:
    title: str
    date: str
    date_label: str
    category: str
    status: str
    summary: str
    location: str
    image: str | None
    link: str | None
    instagram_url: str | None = None


def slugify(value: str, fallback: str = "item") -> str:
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or fallback


def text_from_html(value: str) -> str:
    value = re.sub(r"<script\b[^>]*>.*?</script>", " ", value, flags=re.I | re.S)
    value = re.sub(r"<style\b[^>]*>.*?</style>", " ", value, flags=re.I | re.S)
    value = re.sub(r"<[^>]+>", " ", value)
    value = html.unescape(value).replace("\xa0", " ")
    return re.sub(r"\s+", " ", value).strip()


def shorten(value: str, limit: int = 180) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    if len(value) <= limit:
        return value
    clipped = value[:limit].rsplit(" ", 1)[0].rstrip(",.;:-")
    return f"{clipped}..."


def parse_date(value: str | None) -> datetime:
    if not value:
        return datetime(1970, 1, 1)
    value = value.replace("Z", "+00:00")
    return datetime.fromisoformat(value)


def format_date(value: datetime) -> str:
    return value.strftime("%d/%m/%Y")


def format_month(value: datetime) -> str:
    return f"{MONTHS[value.month - 1]} {value.year}"


def zip_basename(name: str) -> str:
    return posixpath.basename(name.rstrip("/"))


def image_key(value: str) -> str:
    return unquote(html.unescape(value)).replace("\\", "/").split("/")[-1].lower()


def image_name_from_url(value: str) -> str | None:
    parsed = urlparse(html.unescape(value))
    name = posixpath.basename(parsed.path)
    if not name:
        return None
    name = unquote(name)
    ext = os.path.splitext(name)[1].lower()
    if ext not in IMAGE_EXTENSIONS:
        return None
    return name


def extract_instagram_url(content: str) -> str | None:
    match = re.search(r"https://(?:www\.)?instagram\.com/(?:p|reel|tv)/[^\"'<\s]+", content, flags=re.I)
    if not match:
        return None
    return html.unescape(match.group(0)).rstrip("/")


def clean_content(content: str) -> str:
    content = re.sub(r"<script\b[^>]*>.*?</script>", "", content, flags=re.I | re.S)
    content = re.sub(r"<style\b[^>]*>.*?</style>", "", content, flags=re.I | re.S)
    content = re.sub(r"<!--\s*more\s*-->", "", content, flags=re.I)
    content = re.sub(r'href="([^"]+)"_blank"', r'href="\1" target="_blank"', content)
    content = re.sub(r"<br\s*/?>\s*(<br\s*/?>\s*)+", "<br>", content, flags=re.I)
    return content.strip()


def add_lazy_loading(content: str) -> str:
    def replace(match: re.Match[str]) -> str:
        tag = match.group(0)
        if re.search(r"\sloading=", tag, flags=re.I) is None:
            tag = re.sub(r"\s*/?>$", ' loading="lazy">', tag)
        if re.search(r"\salt=", tag, flags=re.I) is None:
            tag = re.sub(r"\s*/?>$", ' alt="">', tag)
        return tag

    return re.sub(r"<img\b[^>]*>", replace, content, flags=re.I)


def rewrite_image_urls(content: str, image_map: dict[str, str], prefix: str) -> tuple[str, str | None, int]:
    first_image: str | None = None
    missing = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal first_image, missing
        attr = match.group(1)
        quote = match.group(2)
        value = match.group(3)
        image_name = image_name_from_url(value)
        if not image_name:
            return match.group(0)
        local = image_map.get(image_key(image_name))
        if local:
            if first_image is None:
                first_image = local
            return f'{attr}={quote}{prefix}{local}{quote}'
        missing += 1
        return match.group(0)

    rewritten = re.sub(r"\b(src|href)=(['\"])([^'\"]+)\2", replace, content, flags=re.I)
    return rewritten, first_image, missing


def find_feed(zf: zipfile.ZipFile) -> str:
    feeds = [info.filename for info in zf.infolist() if info.filename.endswith("/feed.atom")]
    if not feeds:
        raise RuntimeError("Nenhum feed.atom foi encontrado no backup.")
    return feeds[0]


def extract_images(zf: zipfile.ZipFile, output_dir: Path) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    image_map: dict[str, str] = {}
    used_names: set[str] = set()

    for info in zf.infolist():
        name = zip_basename(info.filename)
        ext = os.path.splitext(name)[1].lower()
        if ext not in IMAGE_EXTENSIONS:
            continue

        stem = os.path.splitext(name)[0]
        safe_stem = slugify(stem, "imagem")
        safe_name = f"{safe_stem}{ext}"
        counter = 2
        while safe_name in used_names:
            safe_name = f"{safe_stem}-{counter}{ext}"
            counter += 1

        used_names.add(safe_name)
        target = output_dir / safe_name
        target.write_bytes(zf.read(info.filename))
        image_map.setdefault(image_key(name), f"assets/img/{safe_name}")

    return image_map


def build_posts(feed_xml: str, image_map: dict[str, str]) -> tuple[str, list[Post], int]:
    root = ET.fromstring(feed_xml)
    blog_title = (root.findtext(f"{{{ATOM_NS}}}title") or "Blog da Escola").strip()
    posts: list[Post] = []
    slugs: set[str] = set()
    missing_images = 0

    for entry in root.findall(f"{{{ATOM_NS}}}entry"):
        entry_type = entry.findtext(f"{{{BLOGGER_NS}}}type")
        status = entry.findtext(f"{{{BLOGGER_NS}}}status")
        if entry_type != "POST" or status != "LIVE":
            continue

        published = parse_date(entry.findtext(f"{{{ATOM_NS}}}published"))
        content = entry.findtext(f"{{{ATOM_NS}}}content") or ""
        content = clean_content(content)
        rewritten, cover, missing = rewrite_image_urls(content, image_map, "")
        missing_images += missing
        rewritten = add_lazy_loading(rewritten)
        instagram_url = extract_instagram_url(rewritten)

        excerpt_source = text_from_html(rewritten)
        excerpt = shorten(excerpt_source) or "Registro publicado no blog da escola."
        raw_title = (entry.findtext(f"{{{ATOM_NS}}}title") or "").strip()
        generated_title = not bool(raw_title)
        title = raw_title or shorten(excerpt_source, 72) or f"Publicação de {format_date(published)}"

        labels: list[str] = []
        for category in entry.findall(f"{{{ATOM_NS}}}category"):
            term = (category.attrib.get("term") or "").strip()
            if term and "blogger.com" not in term and term not in labels:
                labels.append(term)

        author = entry.findtext(f"{{{ATOM_NS}}}author/{{{ATOM_NS}}}name") or "EE São José"
        base_slug = f"{published:%Y-%m-%d}-{slugify(title, 'publicacao')}"
        slug = base_slug
        counter = 2
        while slug in slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1
        slugs.add(slug)

        posts.append(
            Post(
                title=title,
                slug=slug,
                published=published,
                date_label=format_date(published),
                author=author.strip(),
                excerpt=excerpt,
                content=rewritten,
                cover=cover,
                labels=labels,
                post_path=f"posts/{slug}.html",
                generated_title=generated_title,
                instagram_url=instagram_url,
            )
        )

    posts.sort(key=lambda post: post.published, reverse=True)
    return blog_title, posts, missing_images


def prefixed_content(content: str, prefix: str) -> str:
    if not prefix:
        return content
    return re.sub(r'\b(src|href)=(["\'])assets/', rf'\1=\2{prefix}assets/', content)


def archive_items(posts: list[Post]) -> list[tuple[str, str, int]]:
    counts: dict[str, int] = {}
    labels: dict[str, str] = {}
    for post in posts:
        key = f"{post.published:%Y-%m}"
        counts[key] = counts.get(key, 0) + 1
        labels[key] = format_month(post.published)
    return [(key, labels[key], counts[key]) for key in sorted(counts.keys(), reverse=True)]


def parse_event_date(value: str) -> tuple[datetime | None, str]:
    if not value:
        return None, "Data a definir"
    try:
        parsed = datetime.fromisoformat(value)
        return parsed, format_date(parsed)
    except ValueError:
        return None, value


def load_events(project_dir: Path) -> list[Event]:
    events_path = project_dir / "data" / "eventos.json"
    if not events_path.exists():
        return []

    raw_data = json.loads(events_path.read_text(encoding="utf-8"))
    raw_events = raw_data.get("eventos", raw_data) if isinstance(raw_data, dict) else raw_data
    events: list[Event] = []

    for raw_event in raw_events:
        if not isinstance(raw_event, dict):
            continue
        title = str(raw_event.get("titulo") or raw_event.get("title") or "").strip()
        if not title:
            continue
        date_value = str(raw_event.get("data") or raw_event.get("date") or "").strip()
        parsed_date, date_label = parse_event_date(date_value)
        events.append(
            Event(
                title=title,
                date=date_value,
                date_label=date_label,
                category=str(raw_event.get("categoria") or raw_event.get("category") or "Evento").strip(),
                status=str(raw_event.get("status") or "Realizado").strip(),
                summary=str(raw_event.get("resumo") or raw_event.get("summary") or "").strip(),
                location=str(raw_event.get("local") or raw_event.get("location") or "").strip(),
                image=str(raw_event.get("imagem") or raw_event.get("image") or "").strip() or None,
                link=str(raw_event.get("link") or "").strip() or None,
                instagram_url=None,
            )
        )

    events.sort(key=lambda event: parse_event_date(event.date)[0] or datetime.min, reverse=True)
    return events


def portal_tags_html(labels: list[str]) -> str:
    if not labels:
        return ""
    return "".join(f'<span class="pill">{html.escape(label)}</span>' for label in labels[:4])


def portal_post_title(post: Post) -> str:
    if post.generated_title and post.instagram_url:
        return f"Registro no Instagram - {post.date_label}"
    return post.title


def portal_post_excerpt(post: Post) -> str:
    generic = "Registro publicado no blog da escola."
    if post.instagram_url and post.excerpt == generic:
        return "Publicação incorporada do Instagram com registro das atividades e eventos da escola."
    return post.excerpt


def portal_media_html(post: Post, css_class: str, prefix: str = "", eager: bool = False) -> str:
    if post.instagram_url and not post.cover:
        return f"""
        <div class="{css_class} is-instagram">
            {portal_cover_html(post, prefix, eager)}
        </div>
        """
    return f"""
    <a class="{css_class}" href="{prefix}{html.escape(post.post_path)}">
        {portal_cover_html(post, prefix, eager)}
    </a>
    """


def portal_cover_html(post: Post, prefix: str = "", eager: bool = False) -> str:
    loading = "eager" if eager else "lazy"
    if post.cover:
        return (
            f'<img src="{prefix}{html.escape(post.cover)}" '
            f'alt="{html.escape(portal_post_title(post))}" loading="{loading}">'
        )
    if post.instagram_url:
        url = html.escape(post.instagram_url)
        return f"""
        <blockquote class="instagram-media instagram-card-embed" data-instgrm-permalink="{url}" data-instgrm-version="14" style="background:#fff; border:0; margin:0 auto; padding:0; width:100%;">
            <a href="{url}" target="_blank" rel="noopener">Ver publicação no Instagram</a>
        </blockquote>
        """
    return """
    <div class="portal-media-fallback">
        <span>EE</span>
        <strong>São José</strong>
    </div>
    """


def portal_shell(
    *,
    blog_title: str,
    title: str,
    css_href: str,
    script_href: str,
    body_html: str,
    prefix: str = "",
    active: str = "home",
    body_class: str = "",
    page_path: str = "/",
    description: str = SITE_DESCRIPTION,
    og_type: str = "website",
) -> str:
    page_url = f"{SITE_ORIGIN}{page_path}"
    escaped_title = html.escape(title)
    escaped_description = html.escape(description, quote=True)
    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="static-blog-importer">
    <title>{escaped_title}</title>
    <!-- social-preview:start -->
    <meta name="description" content="{escaped_description}">
    <link rel="icon" type="image/png" href="/assets/img/logo_escola.png">
    <link rel="apple-touch-icon" href="/assets/img/logo_escola.png">
    <link rel="canonical" href="{page_url}">
    <meta property="og:locale" content="pt_BR">
    <meta property="og:type" content="{og_type}">
    <meta property="og:site_name" content="EE São José">
    <meta property="og:title" content="{escaped_title}">
    <meta property="og:description" content="{escaped_description}">
    <meta property="og:url" content="{page_url}">
    <meta property="og:image" content="{SOCIAL_IMAGE_URL}">
    <meta property="og:image:secure_url" content="{SOCIAL_IMAGE_URL}">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="1280">
    <meta property="og:image:height" content="960">
    <meta property="og:image:alt" content="Vista aérea da Escola Estadual São José">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{escaped_title}">
    <meta name="twitter:description" content="{escaped_description}">
    <meta name="twitter:image" content="{SOCIAL_IMAGE_URL}">
    <!-- social-preview:end -->
    <link rel="stylesheet" href="{css_href}">
    <script src="{script_href}" defer></script>
    <script src="https://www.instagram.com/embed.js" defer></script>
</head>
<body{f' class="{html.escape(body_class)}"' if body_class else ''}>
    {GENERATED}
    {portal_header_html(blog_title, prefix, active)}
    {body_html}
    {portal_footer_html(prefix)}
</body>
</html>
"""


def portal_headline_item_html(post: Post, prefix: str = "") -> str:
    title = portal_post_title(post)
    excerpt = portal_post_excerpt(post)
    search_text = " ".join([title, excerpt, post.date_label, " ".join(post.labels)]).lower()
    return f"""
    <article class="headline-item" data-post data-search-text="{html.escape(search_text)}">
        <a href="{prefix}{html.escape(post.post_path)}">
            <span>{html.escape(post.date_label)}</span>
            <strong>{html.escape(title)}</strong>
        </a>
    </article>
    """


def portal_event_card_html(event: Event, prefix: str = "", embed_instagram: bool = False) -> str:
    search_text = " ".join([event.title, event.summary, event.date_label, event.category, event.location]).lower()
    image = ""
    if event.image:
        image = f'<img src="{prefix}{html.escape(event.image)}" alt="{html.escape(event.title)}" loading="lazy">'
        media_class = "event-card-media"
    elif embed_instagram and event.instagram_url:
        url = html.escape(event.instagram_url)
        image = f"""
        <blockquote class="instagram-media instagram-card-embed" data-instgrm-permalink="{url}" data-instgrm-version="14" style="background:#fff; border:0; margin:0 auto; padding:0; width:100%;">
            <a href="{url}" target="_blank" rel="noopener">Ver publicação no Instagram</a>
        </blockquote>
        """
        media_class = "event-card-media is-instagram"
    else:
        image = '<div class="event-fallback"><span>Evento</span><strong>Registro realizado</strong></div>'
        media_class = "event-card-media"
    link_start = f'<a class="{media_class}" href="{prefix}{html.escape(event.link)}">' if event.link and not event.instagram_url else f'<div class="{media_class}">'
    link_end = "</a>" if event.link else "</div>"
    if event.instagram_url:
        link_end = "</div>"
    action = f'<a class="text-link" href="{prefix}{html.escape(event.link)}">Ver registro</a>' if event.link else ""

    return f"""
    <article class="portal-event-card" data-post data-search-text="{html.escape(search_text)}">
        {link_start}
            {image}
        {link_end}
        <div class="portal-event-body">
            <div class="event-date">
                <span>{html.escape(event.status)}</span>
                <strong>{html.escape(event.date_label)}</strong>
            </div>
            <h3>{html.escape(event.title)}</h3>
            <p>{html.escape(event.summary)}</p>
            <div class="event-details">
                <span>{html.escape(event.category)}</span>
                <span>{html.escape(event.location)}</span>
            </div>
            {action}
        </div>
    </article>
    """


def portal_instagram_posts(posts: list[Post], limit: int = 12) -> list[Post]:
    return [post for post in posts if post.instagram_url][:limit]


def portal_instagram_card_html(post: Post, prefix: str = "") -> str:
    title = portal_post_title(post)
    excerpt = portal_post_excerpt(post)
    search_text = " ".join([title, excerpt, post.date_label, " ".join(post.labels)]).lower()
    return f"""
    <article class="instagram-post-card" data-post data-search-text="{html.escape(search_text)}">
        {portal_media_html(post, "instagram-post-media", prefix)}
        <div class="instagram-post-body">
            <div class="news-meta">
                <span>{html.escape(post.date_label)}</span>
                <span>{html.escape(post.author)}</span>
            </div>
            <h3><a href="{prefix}{html.escape(post.post_path)}">{html.escape(title)}</a></h3>
            <p>{html.escape(excerpt)}</p>
        </div>
    </article>
    """


def portal_instagram_section_html(posts: list[Post]) -> str:
    instagram_posts = portal_instagram_posts(posts)
    if not instagram_posts:
        return """
        <div class="empty-events">
            <strong>Nenhuma postagem do Instagram encontrada</strong>
            <span>Quando o backup trouxer embeds do Instagram, eles aparecerão aqui.</span>
        </div>
        """
    return f"""
    <div class="instagram-grid">
        {''.join(portal_instagram_card_html(post) for post in instagram_posts)}
    </div>
    """


def portal_archive_cards_html(posts: list[Post], prefix: str = "") -> str:
    items = []
    for key, label, count in archive_items(posts):
        items.append(
            f"""
            <a class="archive-chip" href="/#archive-{key}">
                <span>{html.escape(label.title())}</span>
                <strong>{count}</strong>
            </a>
            """
        )
    return "".join(items)


def portal_timeline_html(posts: list[Post]) -> str:
    groups: list[str] = []
    current_month = ""
    open_group = False

    for post in posts:
        month_key = f"{post.published:%Y-%m}"
        if month_key != current_month:
            if open_group:
                groups.append("</div></section>")
            groups.append(
                f"""
                <section class="archive-month" id="archive-{month_key}" data-date-group>
                    <header>
                        <span>{html.escape(format_month(post.published).title())}</span>
                    </header>
                    <div class="archive-news-list">
                """
            )
            current_month = month_key
            open_group = True
        groups.append(portal_archive_item_html(post))

    if open_group:
        groups.append("</div></section>")

    return "".join(groups)


def portal_archive_item_html(post: Post, prefix: str = "") -> str:
    title = portal_post_title(post)
    excerpt = portal_post_excerpt(post)
    search_text = " ".join([title, excerpt, post.date_label, " ".join(post.labels)]).lower()
    if post.cover:
        media = f"""
        <a class="archive-thumb" href="{prefix}{html.escape(post.post_path)}">
            {portal_cover_html(post, prefix)}
        </a>
        """
    elif post.instagram_url:
        media = f"""
        <a class="archive-thumb" href="{prefix}{html.escape(post.post_path)}">
            <div class="portal-instagram-preview">
                <span>Instagram</span>
                <strong>Publicação da escola</strong>
                <small>{html.escape(post.date_label)}</small>
            </div>
        </a>
        """
    else:
        media = f"""
        <a class="archive-thumb" href="{prefix}{html.escape(post.post_path)}">
            <div class="portal-media-fallback"><span>EE</span><strong>São José</strong></div>
        </a>
        """
    return f"""
    <article class="archive-news-item" data-post data-search-text="{html.escape(search_text)}">
        {media}
        <div>
            <span>{html.escape(post.date_label)}</span>
            <h3><a href="{prefix}{html.escape(post.post_path)}">{html.escape(title)}</a></h3>
            <p>{html.escape(excerpt)}</p>
        </div>
    </article>
    """


def portal_admission_html() -> str:
    links = [
        (
            "ENEM - Página do Participante",
            "https://www.gov.br/inep/pt-br/assuntos/sistemas-e-plataformas/enem-pagina-do-participante",
            "Inscrições, cartão de confirmação, resultados e acompanhamento do exame.",
        ),
        (
            "Acesso Único MEC",
            "https://acessounico.mec.gov.br/",
            "Portal dos programas Sisu, Prouni e Fies para ingresso no ensino superior.",
        ),
        (
            "Ingresso UFMS",
            "https://ingresso.ufms.br/",
            "Processos seletivos, Vestibular, PASSE, SiSU e demais formas de ingresso.",
        ),
        (
            "Vestibular UEMS",
            "https://www.uems.br/pro-reitoria/proe/dind/vestibular",
            "Página institucional do processo seletivo vestibular da UEMS.",
        ),
    ]
    cards = "".join(
        f"""
        <a class="admission-card" href="{html.escape(url)}" target="_blank" rel="noopener">
            <span>Inscrição</span>
            <strong>{html.escape(title)}</strong>
            <small>{html.escape(summary)}</small>
        </a>
        """
        for title, url, summary in links
    )
    return f"""
    <section class="content-section admission-section" id="inscricoes" aria-label="Inscrição de vestibular">
        <div class="section-heading">
            <span>Orientação ao estudante</span>
            <h2>Inscrição de vestibular</h2>
            <p>Links rápidos para acompanhar inscrições, resultados e formas de ingresso no ensino superior.</p>
        </div>
        <div class="admission-grid">
            {cards}
        </div>
    </section>
    """


def write_weather_station_page(project_dir: Path, blog_title: str) -> None:
    body = """
    <main class="portal-main weather-station-page">
        <section class="weather-station-hero" aria-labelledby="weather-page-title">
            <div class="weather-station-copy">
                <div class="weather-live-badge">
                    <span aria-hidden="true"></span>
                    Monitoramento em tempo real
                </div>
                <p class="weather-station-kicker">Estação Meteorológica • Vicentina/MS</p>
                <h1 id="weather-page-title">O clima da nossa comunidade, medido aqui na escola.</h1>
                <p class="weather-station-intro">Acompanhe as condições meteorológicas registradas pela estação da EE São José e consulte informações atualizadas sobre chuva, vento, temperatura e muito mais.</p>
                <div class="weather-station-actions">
                    <a class="primary-action weather-panel-link" href="#painel-meteorologico">Ver dados agora</a>
                    <button class="weather-alert-hero-button" type="button" data-open-weather-alerts>Receber alertas</button>
                </div>
                <dl class="weather-station-facts">
                    <div><dt>Localização</dt><dd>EE São José</dd></div>
                    <div><dt>Leituras</dt><dd>Automáticas</dd></div>
                    <div><dt>Acesso</dt><dd>Aberto à comunidade</dd></div>
                </dl>
            </div>
            <figure class="weather-station-photo">
                <img src="/assets/img/img-20220909-083336.jpg" alt="Sensores da estação meteorológica da EE São José ao entardecer">
                <figcaption>
                    <span>Estação da EE São José</span>
                    <strong>Ciência e tecnologia a serviço da comunidade</strong>
                </figcaption>
            </figure>
        </section>

        <section class="weather-sensor-grid" aria-label="Informações disponíveis na estação">
            <article>
                <span class="weather-sensor-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M14 14.76V5a2 2 0 0 0-4 0v9.76a4 4 0 1 0 4 0Z"/><path d="M12 9v8"/></svg></span>
                <div><strong>Temperatura</strong><small>Condições térmicas locais</small></div>
            </article>
            <article>
                <span class="weather-sensor-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3s6 6.1 6 11a6 6 0 0 1-12 0c0-4.9 6-11 6-11Z"/><path d="M9.5 15.5a3 3 0 0 0 4.5 1.8"/></svg></span>
                <div><strong>Umidade</strong><small>Umidade relativa do ar</small></div>
            </article>
            <article>
                <span class="weather-sensor-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 8h10a3 3 0 1 0-3-3"/><path d="M3 12h15a3 3 0 1 1-3 3"/><path d="M3 16h7"/></svg></span>
                <div><strong>Vento</strong><small>Velocidade e direção</small></div>
            </article>
            <article>
                <span class="weather-sensor-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7 15a4 4 0 1 1 1.2-7.8A5.5 5.5 0 0 1 19 9a3 3 0 0 1-1 5.83"/><path d="m8 18-1 2"/><path d="m13 17-1 3"/><path d="m18 18-1 2"/></svg></span>
                <div><strong>Chuva</strong><small>Volume de precipitação</small></div>
            </article>
        </section>

        <section class="weather-dashboard-section" id="painel-meteorologico" aria-labelledby="weather-dashboard-title">
            <header class="weather-dashboard-heading">
                <div>
                    <span>Painel oficial</span>
                    <h2 id="weather-dashboard-title">Dados da estação em tempo real</h2>
                    <p>Os valores abaixo são carregados diretamente do painel oficial da estação.</p>
                </div>
                <a href="https://meteo.eesjv.com.br/" target="_blank" rel="noopener">
                    Abrir painel completo <span aria-hidden="true">↗</span>
                </a>
            </header>
            <div class="legacy-weather-shell" data-weather-shell>
                <div class="weather-frame-toolbar">
                    <span class="weather-frame-dots" aria-hidden="true"><i></i><i></i><i></i></span>
                    <strong>EE São José • Estação meteorológica</strong>
                    <span class="weather-frame-toolbar-actions">
                        <span class="weather-frame-status">Ao vivo</span>
                        <a href="https://meteo.eesjv.com.br/" target="_blank" rel="noopener">Abrir ↗</a>
                    </span>
                </div>
                <div class="weather-frame-container">
                    <div class="weather-frame-loader" data-weather-loader role="status">
                        <span></span>
                        <strong>Carregando dados meteorológicos…</strong>
                        <small>Isso pode levar alguns segundos.</small>
                    </div>
                    <div class="weather-frame-fallback" data-weather-fallback hidden>
                        <span class="weather-frame-fallback-icon" aria-hidden="true">☁</span>
                        <strong>O painel está demorando para responder</strong>
                        <p>Isso pode acontecer por bloqueio de conteúdo externo, conexão instável ou cache do navegador.</p>
                        <div>
                            <button type="button" data-reload-weather>Carregar novamente</button>
                            <a href="https://meteo.eesjv.com.br/" target="_blank" rel="noopener">Abrir painel oficial</a>
                        </div>
                    </div>
                    <iframe
                        class="legacy-weather-frame"
                        data-weather-frame
                        src="https://meteo.eesjv.com.br/"
                        title="Dados em tempo real da Estação Meteorológica da EE São José"
                        loading="eager"
                        allow="fullscreen"
                    ></iframe>
                    <noscript>
                        <p class="weather-frame-noscript">Ative o JavaScript ou <a href="https://meteo.eesjv.com.br/">abra o painel meteorológico diretamente</a>.</p>
                    </noscript>
                </div>
            </div>
        </section>

        <aside class="weather-alert-callout">
            <div class="weather-alert-callout-icon" aria-hidden="true">!</div>
            <div>
                <span>Fique atento ao tempo</span>
                <h2>Receba alertas de tempestades pelo WhatsApp</h2>
                <p>Cadastre sua localidade para receber avisos meteorológicos importantes da região.</p>
            </div>
            <button type="button" data-open-weather-alerts>Quero receber alertas</button>
        </aside>
    </main>
    """
    document = portal_shell(
        blog_title=blog_title,
        title=f"Estação Meteorológica | {blog_title}",
        css_href="/assets/css/style-20260619.css",
        script_href="/assets/js/script-20260619.js",
        body_html=body,
        prefix="../",
        active="weather",
        body_class="weather-station-body",
        page_path="/estacao-meteorologica/",
    )
    weather_dir = project_dir / "estacao-meteorologica"
    weather_dir.mkdir(parents=True, exist_ok=True)
    (weather_dir / "index.html").write_text(document, encoding="utf-8")
    legacy_redirect = """<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8">
<meta http-equiv="refresh" content="0; url=/estacao-meteorologica/">
<script>window.location.replace("/estacao-meteorologica/" + window.location.search + window.location.hash);</script>
</head><body><a href="/estacao-meteorologica/">Abrir Estação Meteorológica</a></body></html>"""
    (project_dir / "estacao-meteorologica.html").write_text(legacy_redirect, encoding="utf-8")


def institutional_post_title(post: Post) -> str:
    return portal_post_title(post)


def find_post_by_keywords(posts: list[Post], keywords: list[str]) -> Post | None:
    normalized_keywords = [slugify(keyword) for keyword in keywords]
    for post in posts:
        haystack = slugify(" ".join([post.title, post.slug, post.excerpt, " ".join(post.labels)]))
        if any(keyword in haystack for keyword in normalized_keywords):
            return post
    return None


def select_visual_posts(posts: list[Post], *, limit: int = 6, exclude_slugs: set[str] | None = None) -> list[Post]:
    exclude_slugs = exclude_slugs or set()
    selected: list[Post] = []
    for post in posts:
        if post.slug in exclude_slugs or not post.cover:
            continue
        selected.append(post)
        if len(selected) == limit:
            break
    return selected


def institutional_hero_post(posts: list[Post]) -> Post:
    visual_posts = [post for post in posts if post.cover]
    return (
        find_post_by_keywords(visual_posts, ["arraia", "mostra cultural", "projeto leitura"])
        or next((post for post in visual_posts if not post.generated_title), posts[0])
    )


def institutional_nav_html(prefix: str = "", active: str = "home") -> str:
    current_home = ""
    current_weather = ' aria-current="page"' if active == "weather" else ""
    return f"""
    <nav class="main-nav" aria-label="Navegação principal">
        <a href="/"{current_home}>Início</a>
        <a href="/#sobre">Sobre</a>
        <a href="/#viagens">Viagens</a>
        <a href="/#avisos">Avisos</a>
        <a href="/#projetos">Projetos</a>
        <a href="/#galeria">Galeria</a>
        <a href="/#instagram">Instagram</a>
        <a href="/#vestibular">Vestibular</a>
        <a href="/estacao-meteorologica/"{current_weather}>Estação meteorológica</a>
        <button class="nav-alert-button" type="button" data-open-weather-alerts>Receber alertas de tempestades</button>
        <a href="/#contato">Contato</a>
    </nav>
    """


def portal_header_html(blog_title: str, prefix: str = "", active: str = "home") -> str:
    return f"""
    <header class="site-header">
        <div class="top-strip">
            <a class="top-school-crest" href="/" aria-label="Escola Estadual São José — página inicial">
                <img src="{prefix}assets/img/logo_escola.png" alt="Brasão da Escola Estadual São José">
            </a>
        </div>
        <div class="brand-row">
            <form class="portal-search" data-search-form>
                <label class="visually-hidden" for="{prefix.replace('.', '').replace('/', '')}portal-search">Pesquisar no acervo</label>
                <input id="{prefix.replace('.', '').replace('/', '')}portal-search" data-search type="search" autocomplete="off" placeholder="Pesquisar no acervo">
                <button type="submit">Buscar</button>
            </form>
        </div>
        {institutional_nav_html(prefix, active)}
    </header>
    """


def portal_footer_html(prefix: str = "") -> str:
    return f"""
    <div class="weather-alert-modal" data-weather-alert-modal hidden aria-hidden="true">
        <div class="weather-alert-dialog" role="dialog" aria-modal="true" aria-labelledby="weather-alert-title">
            <button class="weather-alert-close" type="button" data-close-weather-alerts aria-label="Fechar cadastro">×</button>
            <span class="weather-alert-eyebrow">Alertas pelo WhatsApp</span>
            <h2 id="weather-alert-title">Receber alertas de tempestades</h2>
            <p>Cadastre-se para receber avisos meteorológicos enviados pela estação da EE São José.</p>
            <form class="weather-alert-form" method="POST" action="https://meteo.eesjv.com.br/">
                <label><span>Nome</span><input type="text" name="nome" autocomplete="name" placeholder="Seu nome" required></label>
                <label><span>WhatsApp</span><input type="tel" name="telefone" data-weather-phone autocomplete="tel" placeholder="(67) 99999-9999" required></label>
                <label><span>Endereço, fazenda ou bairro</span><input type="text" name="endereco" autocomplete="street-address" placeholder="Informe sua localidade" required></label>
                <label class="weather-alert-consent">
                    <input type="checkbox" name="whatsapp" value="1" checked required>
                    <span>Aceito receber alertas meteorológicos pelo WhatsApp e sei que posso cancelar a qualquer momento.</span>
                </label>
                <div class="weather-alert-actions">
                    <button class="weather-alert-cancel" type="button" data-close-weather-alerts>Cancelar</button>
                    <button class="weather-alert-submit" type="submit">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>

    <footer class="site-footer" id="rodape">
        <div class="footer-grid">
            <div>
                <a class="footer-brand" href="/">
                    <img src="{prefix}assets/img/logo_escola.png" alt="" aria-hidden="true">
                    <span>
                        <strong>EE São José</strong>
                        <small>Vicentina/MS</small>
                    </span>
                </a>
                <p>Site institucional da Escola Estadual São José, com informações para estudantes, famílias, equipe escolar e comunidade.</p>
            </div>
            <div>
                <h2>Navegação</h2>
                <a href="/#sobre">Sobre a escola</a>
                <a href="/#avisos">Avisos</a>
                <a href="/#projetos">Projetos escolares</a>
                <a href="/#viagens">Viagens do conhecimento</a>
                <a href="/#galeria">Galeria</a>
            </div>
            <div>
                <h2>Serviços</h2>
                <a href="/#vestibular">Inscrição de vestibular</a>
                <a href="/estacao-meteorologica/">Estação meteorológica</a>
                <a href="/#instagram">Instagram</a>
                <a href="{prefix}admin/">Área administrativa</a>
            </div>
        </div>
        <div class="footer-bottom">
            <span>Escola Estadual São José</span>
            <a href="/">Voltar ao topo</a>
        </div>
    </footer>
    """


def hero_section_html(blog_title: str, posts: list[Post]) -> str:
    post = institutional_hero_post(posts)
    return f"""
    <section class="hero-section" id="inicio" aria-label="Página inicial">
        <div class="hero-copy">
            <span class="eyebrow">Vicentina/MS</span>
            <h1>{html.escape(blog_title)}: escola, comunidade e aprendizagem em movimento.</h1>
            <p>Um espaço institucional para acompanhar avisos, projetos, registros da comunidade escolar e serviços importantes para estudantes e famílias.</p>
            <div class="hero-actions">
                <a class="primary-action" href="/#avisos">Ver avisos</a>
                <a class="secondary-action" href="/#sobre">Conhecer a escola</a>
            </div>
        </div>
        <a class="hero-media" href="{html.escape(post.post_path)}" aria-label="{html.escape(institutional_post_title(post))}">
            {portal_cover_html(post, eager=True)}
        </a>
    </section>
    """


def about_section_html() -> str:
    return """
    <section class="content-section about-section" id="sobre" aria-label="Sobre a escola">
        <div class="section-heading">
            <span>Sobre a escola</span>
            <h2>Educação pública com identidade, acolhimento e participação.</h2>
            <p>A EE São José atua junto à comunidade escolar para fortalecer aprendizagens, projetos pedagógicos e experiências que aproximam escola, família e território.</p>
        </div>
        <div class="about-grid">
            <article>
                <span>Missão</span>
                <p>Contribuir para a formação integral dos estudantes, desenvolvendo capacidades intelectuais, profissionais e socioemocionais.</p>
            </article>
            <article>
                <span>Visão</span>
                <p>Ser reconhecida como uma escola acolhedora, inclusiva e comprometida com ensino de qualidade.</p>
            </article>
            <article>
                <span>Comunidade</span>
                <p>Valorizar a participação de estudantes, famílias, professores e parceiros locais na vida escolar.</p>
            </article>
        </div>
    </section>
    """


def notices_section_html(events: list[Event]) -> str:
    if not events:
        cards = """
        <div class="notice-empty">
            <strong>Nenhum aviso publicado no momento</strong>
            <span>Quando houver comunicados oficiais, eles aparecerão nesta área.</span>
        </div>
        """
    else:
        cards = "".join(portal_event_card_html(event) for event in events)
    return f"""
    <section class="content-section notice-section" id="avisos" aria-label="Notícias e avisos">
        <div class="section-heading compact-heading">
            <span>Notícias e avisos</span>
            <h2>Comunicados oficiais</h2>
            <p>Informações institucionais publicadas pela escola.</p>
        </div>
        <div class="notice-grid">
            {cards}
        </div>
    </section>
    """


def project_card_html(title: str, summary: str, post: Post | None, fallback_image: str | None = None) -> str:
    image = ""
    link = "#projetos"
    media_tag = "a"
    if post:
        link = post.post_path
        if post.cover or post.instagram_url:
            image = portal_cover_html(post)
            if post.instagram_url and not post.cover:
                media_tag = "div"
        elif fallback_image:
            image = f'<img src="{html.escape(fallback_image)}" alt="{html.escape(title)}" loading="lazy">'
        else:
            image = '<div class="portal-media-fallback"><span>EE</span><strong>São José</strong></div>'
    elif fallback_image:
        image = f'<img src="{html.escape(fallback_image)}" alt="{html.escape(title)}" loading="lazy">'
    else:
        image = '<div class="portal-media-fallback"><span>EE</span><strong>São José</strong></div>'
    if media_tag == "div":
        media = f'<div class="project-media is-instagram">{image}</div>'
    else:
        media = f'<a class="project-media" href="{html.escape(link)}">{image}</a>'
    return f"""
    <article class="project-card">
        {media}
        <div class="project-body">
            <h3><a href="{html.escape(link)}">{html.escape(title)}</a></h3>
            <p>{html.escape(summary)}</p>
        </div>
    </article>
    """


def projects_section_html(posts: list[Post]) -> str:
    specs = [
        ("Horta escolar", "Aprendizagem, cuidado ambiental e práticas sustentáveis no cotidiano escolar.", ["horta escolar", "horta"]),
        ("Leitura viva", "Projetos de leitura e expressão para fortalecer criatividade e protagonismo estudantil.", ["leitura viva", "menino do dedo verde"]),
        ("Esporte na escola", "Vivências esportivas que estimulam cooperação, disciplina e saúde.", ["tenis de mesa", "badminton", "volei", "jogos interescolares"]),
        ("Arte e cultura", "Atividades culturais que valorizam talentos, memória e participação da comunidade.", ["mostra cultural", "arte e cultura", "arraia"]),
    ]
    cards = []
    used: set[str] = set()
    for title, summary, keywords in specs:
        post = find_post_by_keywords([item for item in posts if item.slug not in used], keywords)
        if post:
            used.add(post.slug)
        cards.append(project_card_html(title, summary, post))
    return f"""
    <section class="content-section projects-section" id="projetos" aria-label="Projetos escolares">
        <div class="section-heading">
            <span>Projetos escolares</span>
            <h2>Experiências que conectam sala de aula, território e futuro.</h2>
            <p>Destaques de ações pedagógicas, culturais, esportivas e ambientais realizadas pela escola.</p>
        </div>
        <div class="project-grid">
            {''.join(cards)}
        </div>
    </section>
    """


def gallery_section_html(posts: list[Post]) -> str:
    selected = select_visual_posts(posts, limit=6)
    cards = "".join(
        f"""
        <a class="gallery-card" href="{html.escape(post.post_path)}">
            {portal_cover_html(post)}
            <span>{html.escape(institutional_post_title(post))}</span>
        </a>
        """
        for post in selected
    )
    return f"""
    <section class="content-section gallery-section" id="galeria" aria-label="Galeria e destaques">
        <div class="section-heading compact-heading">
            <span>Galeria</span>
            <h2>Destaques da escola</h2>
            <p>Registros visuais de atividades e momentos da comunidade escolar.</p>
        </div>
        <div class="gallery-grid">
            {cards}
        </div>
    </section>
    """


def instagram_section_html(posts: list[Post]) -> str:
    return f"""
    <section class="content-section instagram-section" id="instagram" aria-label="Instagram da escola">
        <div class="section-heading compact-heading">
            <span>Rede social</span>
            <h2>Instagram da escola</h2>
            <p>Publicações recentes incorporadas diretamente do perfil oficial.</p>
        </div>
        {portal_instagram_section_html(posts)}
    </section>
    """


def admission_section_html() -> str:
    return portal_admission_html().replace('id="inscricoes"', 'id="vestibular"')


def contact_section_html() -> str:
    return """
    <section class="content-section contact-section" id="contato" aria-label="Contato e localização">
        <div class="section-heading">
            <span>Contato e localização</span>
            <h2>Informações para famílias, estudantes e visitantes.</h2>
            <p>Procure a escola para orientações sobre matrícula, rotina escolar, projetos e atendimento à comunidade.</p>
        </div>
        <div class="contact-grid">
            <article class="contact-map-card">
                <span>Localidade</span>
                <strong>Distrito de São José</strong>
                <small>Vicentina/MS</small>
                <div class="school-map">
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7728649.373575364!2d-58.198185!3d-18.9422543!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9489697c892539d3%3A0x23a89196b8475996!2sEscola%20Estadual%20S%C3%A3o%20Jos%C3%A9!5e0!3m2!1spt-BR!2sbr!4v1781896192979!5m2!1spt-BR!2sbr"
                        title="Localização da Escola Estadual São José no Google Maps"
                        loading="lazy"
                        allowfullscreen
                        referrerpolicy="no-referrer-when-downgrade"
                    ></iframe>
                </div>
            </article>
            <article>
                <span>Instagram</span>
                <strong>@eesjms</strong>
                <a href="https://www.instagram.com/eesjms/" target="_blank" rel="noopener">Abrir perfil</a>
            </article>
            <article>
                <span>Estação</span>
                <strong>Monitoramento meteorológico</strong>
                <a href="/estacao-meteorologica/">Abrir painel</a>
            </article>
        </div>
    </section>
    """


def write_portal_index(project_dir: Path, blog_title: str, posts: list[Post], events: list[Event]) -> None:
    body = f"""
    <main class="portal-main">
        {hero_section_html(blog_title, posts)}
        {about_section_html()}
        {notices_section_html(events)}
        {projects_section_html(posts)}
        {gallery_section_html(posts)}
        {instagram_section_html(posts)}
        {admission_section_html()}
        {contact_section_html()}

        <section class="content-section archive-section" id="arquivo" aria-label="Arquivo do blog">
            <div class="section-heading compact-heading">
                <span>Acervo</span>
                <h2>Arquivo histórico</h2>
                <p>Publicações importadas do blog anterior da escola.</p>
            </div>
            <div class="archive-chip-grid">
                {portal_archive_cards_html(posts)}
            </div>
            <p class="empty-state" data-empty-state hidden>Nenhuma publicação encontrada.</p>
            {portal_timeline_html(posts)}
        </section>
    </main>
    """
    document = portal_shell(
        blog_title=blog_title,
        title=f"{blog_title} | Site institucional",
        css_href="/assets/css/style-20260619.css?v=20260622-instagram-cards",
        script_href="/assets/js/script-20260619.js?v=20260622-instagram-cards",
        body_html=body,
        page_path="/",
    )
    (project_dir / "index.html").write_text(document, encoding="utf-8")


def write_portal_post_pages(project_dir: Path, blog_title: str, posts: list[Post]) -> None:
    posts_dir = project_dir / "posts"
    posts_dir.mkdir(exist_ok=True)

    for index, post in enumerate(posts):
        previous_post = posts[index + 1] if index + 1 < len(posts) else None
        next_post = posts[index - 1] if index > 0 else None
        more_posts = [item for item in posts[:6] if item.slug != post.slug][:3]
        nav_items = []
        if previous_post:
            nav_items.append(f'<a href="{html.escape(previous_post.slug)}.html">Publicação anterior</a>')
        nav_items.append('<a href="/#arquivo">Voltar ao acervo</a>')
        if next_post:
            nav_items.append(f'<a href="{html.escape(next_post.slug)}.html">Próxima publicação</a>')

        content = prefixed_content(post.content, "../")
        title = portal_post_title(post)
        excerpt = portal_post_excerpt(post)
        body = f"""
        <main class="portal-main">
            <div class="post-page-grid">
                <article class="post-article" data-post data-search-text="{html.escape((title + ' ' + excerpt).lower())}">
                    <header class="post-hero">
                        <a class="back-link" href="/#arquivo">Acervo</a>
                        <span>{html.escape(post.date_label)}</span>
                        <h1>{html.escape(title)}</h1>
                        <p>{html.escape(excerpt)}</p>
                        <div class="pill-row">{portal_tags_html(post.labels)}</div>
                    </header>
                    <div class="post-content">
                        {content}
                    </div>
                    <nav class="post-navigation" aria-label="Navegação entre publicações">
                        {''.join(nav_items)}
                    </nav>
                </article>
                <aside class="related-panel" aria-label="Publicações recentes">
                    <div class="panel-title">
                        <span>Continue lendo</span>
                        <h2>Recentes</h2>
                    </div>
                    <div class="related-list">
                        {''.join(portal_headline_item_html(item, "../") for item in more_posts)}
                    </div>
                </aside>
            </div>
        </main>
        """
        document = portal_shell(
            blog_title=blog_title,
            title=f"{title} | {blog_title}",
            css_href="/assets/css/style-20260619.css",
            script_href="/assets/js/script-20260619.js",
            body_html=body,
            prefix="../",
            active="posts",
            page_path=f"/posts/{post.slug}.html",
            description=excerpt or SITE_DESCRIPTION,
            og_type="article",
        )
        (posts_dir / f"{post.slug}.html").write_text(document, encoding="utf-8")


def write_portal_assets(project_dir: Path) -> None:
    css = """:root {
    --page: #f7f8ff;
    --surface: #ffffff;
    --surface-soft: #fff4ea;
    --ink: #111338;
    --muted: #62657b;
    --line: #dedff0;
    --brand: #1b03b9;
    --brand-dark: #100646;
    --red: #e60000;
    --orange: #ff8128;
    --orange-soft: #fff1e6;
    --blue-soft: #ecebff;
    --shadow: 0 18px 50px rgba(27, 3, 185, 0.12);
}

* {
    box-sizing: border-box;
}

html {
    scroll-behavior: smooth;
}

body {
    margin: 0;
    background:
        radial-gradient(circle at 10% 0%, rgba(255, 129, 40, 0.14), transparent 270px),
        radial-gradient(circle at 92% 4%, rgba(230, 0, 0, 0.10), transparent 260px),
        linear-gradient(180deg, rgba(27, 3, 185, 0.07), transparent 430px),
        var(--page);
    color: var(--ink);
    font-family: Arial, Helvetica, sans-serif;
    overflow-x: hidden;
}

a {
    color: inherit;
    text-decoration: none;
}

img {
    display: block;
    max-width: 100%;
}

button,
input {
    font: inherit;
}

h1,
h2,
h3,
p {
    margin-top: 0;
}

h1,
h2,
h3 {
    overflow-wrap: anywhere;
}

:focus-visible {
    outline: 3px solid rgba(255, 129, 40, 0.82);
    outline-offset: 3px;
}

.visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    overflow: hidden;
    clip: rect(0 0 0 0);
    white-space: nowrap;
    border: 0;
}

.site-header {
    position: sticky;
    top: 0;
    z-index: 30;
    border-top: 5px solid var(--brand);
    border-bottom: 1px solid rgba(222, 223, 240, 0.94);
    background: rgba(255, 255, 255, 0.96);
    backdrop-filter: blur(16px);
}

.top-strip,
.brand-row,
.main-nav,
.portal-main {
    width: min(1220px, calc(100% - 40px));
    margin: 0 auto;
}

.top-strip {
    display: flex;
    justify-content: center;
    gap: 16px;
    text-align: center;
    padding: 8px 0;
    color: var(--muted);
    font-size: 0.78rem;
    font-weight: 800;
    text-transform: uppercase;
}

.top-strip a {
    color: var(--brand);
}

.brand-row {
    display: grid;
    grid-template-columns: minmax(260px, 1fr) minmax(260px, 430px);
    gap: 22px;
    align-items: center;
    padding: 12px 0 14px;
}

.school-brand {
    display: flex;
    align-items: center;
    gap: 14px;
    min-width: 0;
}

.brand-logo {
    width: 78px;
    height: 78px;
    object-fit: contain;
    filter: drop-shadow(0 10px 16px rgba(16, 6, 70, 0.20));
}

.school-brand strong {
    display: block;
    color: var(--brand-dark);
    font-size: clamp(1.34rem, 2.6vw, 2rem);
    line-height: 1;
}

.school-brand small {
    display: block;
    margin-top: 6px;
    color: var(--muted);
    font-size: 0.95rem;
}

.portal-search {
    display: flex;
    gap: 8px;
    min-width: 0;
}

.portal-search input {
    width: 100%;
    min-width: 0;
    border: 1px solid var(--line);
    border-radius: 8px;
    background: #fff;
    color: var(--ink);
    padding: 12px 13px;
}

.portal-search button,
.primary-action,
.secondary-action,
.back-link {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border: 0;
    border-radius: 8px;
    cursor: pointer;
    font-weight: 900;
    min-height: 44px;
    padding: 12px 16px;
    white-space: nowrap;
}

.portal-search button,
.primary-action {
    background: var(--brand);
    color: #fff;
}

.secondary-action,
.back-link {
    border: 1px solid rgba(255, 255, 255, 0.55);
    background: rgba(255, 255, 255, 0.16);
    color: #fff;
}

.main-nav {
    display: flex;
    justify-content: center;
    gap: 6px;
    align-items: center;
    border-top: 1px solid var(--line);
    overflow-x: auto;
    padding: 8px 0;
}

.main-nav a,
.nav-alert-button {
    border-radius: 8px;
    color: #55586f;
    flex: 0 0 auto;
    font-size: 0.92rem;
    font-weight: 900;
    padding: 10px 12px;
}

.nav-alert-button {
    border: 0;
    background: transparent;
    cursor: pointer;
    font-family: inherit;
}

.main-nav a:hover,
.nav-alert-button:hover,
.nav-alert-button:focus-visible,
.main-nav a[aria-current="page"] {
    background: var(--orange-soft);
    color: var(--brand);
}

.weather-alert-modal {
    position: fixed;
    inset: 0;
    z-index: 100;
    display: grid;
    place-items: center;
    overflow-y: auto;
    background: rgba(16, 6, 70, 0.72);
    backdrop-filter: blur(7px);
    padding: 20px;
}

.weather-alert-modal[hidden] {
    display: none;
}

.weather-alert-dialog {
    position: relative;
    width: min(100%, 520px);
    border: 1px solid var(--line);
    border-radius: 14px;
    background: var(--surface);
    box-shadow: 0 28px 80px rgba(16, 6, 70, 0.28);
    padding: clamp(24px, 5vw, 38px);
}

.weather-alert-close {
    position: absolute;
    top: 12px;
    right: 14px;
    width: 40px;
    height: 40px;
    border: 0;
    border-radius: 50%;
    background: var(--page);
    color: var(--brand-dark);
    cursor: pointer;
    font-size: 1.6rem;
}

.weather-alert-eyebrow {
    color: var(--orange);
    font-size: 0.78rem;
    font-weight: 900;
    text-transform: uppercase;
}

.weather-alert-dialog h2 {
    margin: 8px 42px 10px 0;
    color: var(--brand-dark);
    font-size: clamp(1.65rem, 4vw, 2.3rem);
    line-height: 1.08;
}

.weather-alert-dialog > p {
    color: var(--muted);
    line-height: 1.55;
}

.weather-alert-form {
    display: grid;
    gap: 16px;
    margin-top: 22px;
}

.weather-alert-form label:not(.weather-alert-consent) {
    display: grid;
    gap: 7px;
    color: var(--brand-dark);
    font-size: 0.9rem;
    font-weight: 800;
}

.weather-alert-form input[type="text"],
.weather-alert-form input[type="tel"] {
    width: 100%;
    border: 1px solid var(--line);
    border-radius: 9px;
    background: #fff;
    padding: 12px 13px;
}

.weather-alert-consent {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 10px;
    align-items: start;
    color: var(--muted);
    font-size: 0.87rem;
    line-height: 1.45;
}

.weather-alert-consent input {
    margin-top: 3px;
}

.weather-alert-actions {
    display: flex;
    justify-content: flex-end;
    gap: 10px;
    margin-top: 4px;
}

.weather-alert-actions button {
    min-height: 44px;
    border: 0;
    border-radius: 8px;
    cursor: pointer;
    font-weight: 900;
    padding: 11px 16px;
}

.weather-alert-cancel {
    background: var(--page);
    color: var(--muted);
}

.weather-alert-submit {
    background: #16803c;
    color: #fff;
}

body.has-open-modal {
    overflow: hidden;
}

.portal-main {
    padding: 28px 0 58px;
}

.hero-section {
    position: relative;
    display: grid;
    grid-template-columns: minmax(0, 1fr) minmax(360px, 0.82fr);
    gap: 22px;
    align-items: stretch;
    max-width: 100%;
    min-height: 520px;
    border-radius: 8px;
    overflow: hidden;
    background:
        linear-gradient(135deg, rgba(27, 3, 185, 0.95), rgba(230, 0, 0, 0.86) 62%, rgba(255, 129, 40, 0.92));
    box-shadow: var(--shadow);
}

.hero-copy {
    display: grid;
    align-content: center;
    gap: 18px;
    min-width: 0;
    padding: clamp(28px, 6vw, 64px);
    color: #fff;
}

.eyebrow,
.section-heading span,
.panel-title span,
.news-meta,
.archive-month header span,
.archive-news-item > div > span,
.post-hero > span,
.contact-grid span,
.about-grid span,
.admission-card span {
    color: var(--orange);
    font-size: 0.78rem;
    font-weight: 900;
    letter-spacing: 0;
    text-transform: uppercase;
}

.hero-copy .eyebrow {
    color: #fff;
}

.hero-copy h1 {
    max-width: 820px;
    margin-bottom: 0;
    font-size: clamp(2.35rem, 5.6vw, 5.15rem);
    line-height: 0.98;
}

.hero-copy p {
    max-width: 650px;
    margin-bottom: 0;
    color: rgba(255, 255, 255, 0.90);
    font-size: 1.08rem;
    line-height: 1.6;
    overflow-wrap: break-word;
}

.hero-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
}

.hero-media {
    min-width: 0;
    min-height: 420px;
    overflow: hidden;
}

.hero-media img,
.hero-media .portal-media-fallback {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.content-section {
    margin-top: 38px;
    scroll-margin-top: 160px;
}

.section-heading {
    display: grid;
    gap: 8px;
    max-width: 780px;
    margin-bottom: 18px;
}

.section-heading h2,
.panel-title h2 {
    color: var(--brand-dark);
    font-size: clamp(1.75rem, 4vw, 3.05rem);
    line-height: 1.04;
    margin-bottom: 0;
}

.compact-heading h2,
.panel-title h2 {
    font-size: clamp(1.55rem, 3vw, 2.25rem);
}

.section-heading p {
    color: var(--muted);
    line-height: 1.62;
    margin-bottom: 0;
}

.about-grid,
.contact-grid,
.admission-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 14px;
}

.about-grid article,
.contact-grid article,
.admission-card,
.instagram-post-card,
.project-card,
.archive-chip,
.archive-news-item,
.post-article,
.related-panel {
    border: 1px solid var(--line);
    border-radius: 8px;
    background: var(--surface);
    box-shadow: 0 12px 34px rgba(16, 6, 70, 0.06);
}

.about-grid article,
.contact-grid article {
    display: grid;
    gap: 8px;
    padding: 20px;
}

.about-grid p,
.contact-grid small {
    color: var(--muted);
    line-height: 1.56;
    margin-bottom: 0;
}

.notice-grid {
    display: grid;
    gap: 14px;
}

.cms-notice-card {
    display: grid;
    gap: 8px;
    width: min(100%, 760px);
    border: 1px solid #f4cda8;
    border-radius: 8px;
    background: var(--surface);
    box-shadow: 0 12px 34px rgba(16, 6, 70, 0.06);
    padding: 18px;
}

.cms-notice-card > span {
    color: var(--orange);
    font-size: 0.78rem;
    font-weight: 900;
    text-transform: uppercase;
}

.cms-notice-card h3,
.cms-notice-card p {
    margin-bottom: 0;
}

.cms-notice-card h3 {
    color: var(--brand-dark);
}

.cms-notice-card p {
    color: var(--muted);
    line-height: 1.56;
}

.notice-empty,
.empty-events,
.empty-state {
    display: grid;
    gap: 6px;
    width: min(100%, 620px);
    border: 1px solid #f4cda8;
    border-radius: 8px;
    background: var(--orange-soft);
    color: #54435b;
    padding: 16px;
}

.project-grid {
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: 16px;
}

.project-card {
    overflow: hidden;
}

.project-media,
.gallery-card {
    display: block;
    overflow: hidden;
    background: var(--surface-soft);
}

.project-media {
    aspect-ratio: 4 / 3;
}

.project-media.is-instagram {
    position: relative;
    background: #fff;
}

.project-media.is-instagram .instagram-card-embed,
.project-media.is-instagram iframe {
    width: 100% !important;
    min-width: 100% !important;
    max-width: none !important;
    margin: 0 !important;
}

.project-media img,
.project-media .portal-media-fallback,
.gallery-card img,
.gallery-card .portal-media-fallback,
.archive-thumb img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 220ms ease;
}

.project-card:hover img,
.gallery-card:hover img,
.archive-news-item:hover img {
    transform: scale(1.035);
}

.project-body {
    display: grid;
    gap: 8px;
    padding: 16px;
}

.project-body h3,
.instagram-post-card h3,
.archive-news-item h3 {
    color: var(--brand-dark);
    font-size: 1.08rem;
    line-height: 1.24;
    margin-bottom: 0;
}

.project-body p,
.instagram-post-card p,
.archive-news-item p {
    color: var(--muted);
    line-height: 1.56;
    margin-bottom: 0;
}

.gallery-grid {
    display: grid;
    grid-template-columns: repeat(6, minmax(0, 1fr));
    gap: 10px;
}

.gallery-card {
    position: relative;
    min-height: 190px;
    border-radius: 8px;
    color: #fff;
}

.gallery-card:nth-child(1),
.gallery-card:nth-child(4) {
    grid-column: span 2;
    min-height: 260px;
}

.gallery-card:nth-child(5),
.gallery-card:nth-child(6) {
    grid-column: span 3;
    min-height: 260px;
}

.gallery-card.cms-gallery-card {
    grid-column: span 2;
    min-height: 260px;
}

.gallery-card img,
.gallery-card .portal-media-fallback {
    position: absolute;
    inset: 0;
}

.gallery-card::after {
    content: "";
    position: absolute;
    inset: 0;
    background: linear-gradient(180deg, transparent, rgba(16, 6, 70, 0.78));
}

.gallery-card span {
    position: absolute;
    inset: auto 12px 12px;
    z-index: 1;
    font-weight: 900;
    line-height: 1.25;
}

.instagram-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 16px;
    align-items: start;
}

.instagram-post-card {
    align-self: start;
    overflow: hidden;
}

.instagram-post-media {
    display: block;
    width: 100%;
    height: auto;
    overflow: visible;
    background: #fff;
    border-bottom: 1px solid var(--line);
}

.instagram-post-media.has-local-preview {
    aspect-ratio: 4 / 3;
    overflow: hidden;
}

.instagram-post-media iframe {
    display: block;
    width: 100% !important;
    min-width: 100% !important;
    max-width: none !important;
    margin: 0 !important;
}

.instagram-card-embed {
    display: block;
    width: 100% !important;
    min-width: 100% !important;
    max-width: none !important;
    margin: 0 !important;
}

.instagram-local-preview {
    position: relative;
    display: block;
    width: 100%;
    height: 100%;
    margin: 0;
    overflow: hidden;
    background:
        radial-gradient(circle at 25% 20%, rgba(255, 255, 255, 0.22), transparent 130px),
        linear-gradient(145deg, #2410c2, #a80052 68%, #ed0015);
}

.instagram-local-preview img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 360ms ease;
}

.instagram-local-preview:hover img {
    transform: scale(1.045);
}

.instagram-local-preview::after {
    position: absolute;
    inset: 45% 0 0;
    background: linear-gradient(transparent, rgba(16, 6, 70, 0.82));
    content: "";
}

.instagram-local-preview > span {
    position: absolute;
    z-index: 1;
    right: 14px;
    bottom: 14px;
    left: 14px;
    display: flex;
    align-items: end;
    justify-content: space-between;
    gap: 10px;
    color: #fff;
    filter: drop-shadow(0 2px 8px rgba(15, 0, 45, 0.8));
}

.instagram-local-preview > span strong,
.instagram-local-preview > span small {
    display: block;
}

.instagram-local-preview > span strong {
    font-size: 0.96rem;
}

.instagram-local-preview > span small {
    border-radius: 999px;
    background: rgba(255, 255, 255, 0.2);
    font-weight: 900;
    padding: 5px 8px;
}

.instagram-local-preview.is-fallback img {
    display: none;
}

.instagram-local-preview.is-fallback::before {
    position: absolute;
    inset: 0;
    display: grid;
    place-items: center;
    background: url("../img/logo_escola.png") center / 92px auto no-repeat;
    content: "";
    filter: drop-shadow(0 10px 20px rgba(20, 0, 65, 0.32));
}

.instagram-post-body {
    display: none;
}

.instagram-post-body h3,
.instagram-post-body p {
    display: -webkit-box;
    overflow: hidden;
    -webkit-box-orient: vertical;
}

.instagram-post-body h3 {
    -webkit-line-clamp: 2;
}

.instagram-post-body p {
    -webkit-line-clamp: 3;
}

.cms-post-page {
    max-width: 1100px;
}

.cms-post-media {
    overflow: hidden;
    border-bottom: 1px solid var(--line);
    background: var(--surface-soft);
}

.cms-post-media > img {
    width: 100%;
    max-height: 720px;
    object-fit: cover;
}

.cms-post-media .instagram-media {
    margin: 0 auto !important;
}

.cms-page-header .brand-row {
    min-height: 100px;
}

.weather-station-page {
    padding-top: 22px;
}

.weather-station-heading {
    max-width: 920px;
    margin: 0 auto 22px;
    text-align: center;
}

.weather-station-heading span {
    color: var(--orange);
    font-size: 0.78rem;
    font-weight: 900;
    text-transform: uppercase;
}

.weather-station-heading h1 {
    margin: 8px 0 10px;
    color: var(--brand-dark);
    font-size: clamp(2rem, 5vw, 3.8rem);
    line-height: 1.02;
}

.weather-station-heading p {
    color: var(--muted);
    line-height: 1.6;
}

.legacy-weather-shell {
    width: min(100%, 1100px);
    margin: 0 auto;
    border: 1px solid var(--line);
    border-radius: 12px;
    overflow: hidden;
    background: #f7f6f1;
    box-shadow: var(--shadow);
}

.legacy-weather-frame {
    display: block;
    width: 100%;
    height: 1050px;
    border: 0;
    background: #fff;
}

.weather-station-actions {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 10px;
    margin-top: 22px;
}

.weather-station-actions .secondary-station-link {
    display: inline-flex;
    min-height: 44px;
    align-items: center;
    justify-content: center;
    border: 1px solid var(--line);
    border-radius: 8px;
    background: var(--surface);
    color: var(--brand);
    font-weight: 900;
    padding: 11px 16px;
}

.news-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
}

.admission-grid {
    grid-template-columns: repeat(4, minmax(0, 1fr));
}

.admission-card {
    display: grid;
    align-content: start;
    gap: 8px;
    min-height: 170px;
    padding: 18px;
}

.admission-card strong,
.contact-grid strong {
    color: var(--brand-dark);
    font-size: 1.08rem;
    line-height: 1.25;
}

.admission-card small {
    color: var(--muted);
    line-height: 1.46;
}

.contact-grid a,
.text-link {
    color: var(--brand);
    font-weight: 900;
}

.archive-chip-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
    gap: 10px;
}

.archive-chip {
    display: flex;
    justify-content: space-between;
    gap: 10px;
    align-items: center;
    padding: 12px 14px;
}

.archive-chip strong {
    color: var(--brand);
}

.archive-month {
    margin-top: 22px;
}

.archive-month header {
    border-bottom: 1px solid var(--line);
    margin-bottom: 12px;
    padding-bottom: 8px;
}

.archive-news-list {
    display: grid;
    gap: 10px;
}

.archive-news-item {
    display: grid;
    grid-template-columns: 140px minmax(0, 1fr);
    gap: 14px;
    overflow: hidden;
    padding: 10px;
}

.archive-thumb {
    display: block;
    min-height: 98px;
    overflow: hidden;
    border-radius: 8px;
    background: var(--surface-soft);
}

.archive-news-item > div {
    display: grid;
    align-content: center;
    gap: 6px;
    min-width: 0;
}

.portal-media-fallback,
.portal-instagram-preview,
.event-fallback {
    display: grid;
    place-items: center;
    gap: 6px;
    min-height: 160px;
    background: linear-gradient(135deg, var(--brand), var(--red) 58%, var(--orange));
    color: #fff;
    text-align: center;
    padding: 18px;
}

.post-page-grid {
    display: grid;
    grid-template-columns: minmax(0, 1fr) minmax(260px, 340px);
    gap: 20px;
    align-items: start;
}

.post-hero {
    display: grid;
    gap: 12px;
    border-bottom: 1px solid var(--line);
    background: linear-gradient(135deg, #fff, var(--orange-soft));
    padding: clamp(22px, 5vw, 46px);
}

.post-hero h1 {
    color: var(--brand-dark);
    font-size: clamp(2rem, 5vw, 4rem);
    line-height: 1.03;
    margin-bottom: 0;
}

.post-hero p {
    max-width: 820px;
    color: var(--muted);
    font-size: 1.06rem;
    line-height: 1.65;
    margin-bottom: 0;
}

.post-content {
    padding: clamp(20px, 4vw, 42px);
}

.post-content,
.post-content p {
    color: #273047;
    line-height: 1.72;
}

.post-content img {
    width: auto;
    max-height: 780px;
    border-radius: 8px;
    margin: 18px auto;
}

.post-content iframe,
.post-content blockquote {
    max-width: 100%;
}

.post-navigation {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    border-top: 1px solid var(--line);
    padding: 18px;
}

.post-navigation a {
    border: 1px solid var(--line);
    border-radius: 8px;
    color: var(--brand);
    font-weight: 900;
    padding: 10px 12px;
}

.related-panel {
    position: sticky;
    top: 164px;
    display: grid;
    gap: 14px;
    padding: 18px;
}

.related-list {
    display: grid;
    gap: 10px;
}

.headline-item a {
    display: grid;
    gap: 7px;
    border-top: 1px solid var(--line);
    padding-top: 12px;
}

.headline-item:first-child a {
    border-top: 0;
    padding-top: 0;
}

.headline-item strong {
    color: var(--brand-dark);
    line-height: 1.32;
}

[hidden] {
    display: none !important;
}

.site-footer {
    margin-top: 20px;
    border-top: 1px solid var(--line);
    color: #dfe0ff;
    background: var(--brand-dark);
    padding: 34px 0;
}

.footer-grid {
    display: grid;
    grid-template-columns: minmax(0, 1.4fr) repeat(2, minmax(180px, 0.8fr));
    gap: 28px;
    width: min(1220px, calc(100% - 40px));
    margin: 0 auto;
}

.footer-brand {
    display: flex;
    align-items: center;
    gap: 12px;
    color: #fff;
}

.footer-brand img {
    width: 58px;
    height: 58px;
    object-fit: contain;
}

.site-footer p,
.site-footer small {
    color: #c8c9ff;
    line-height: 1.58;
}

.site-footer h2 {
    color: #fff;
    font-size: 1rem;
}

.site-footer a {
    display: block;
    color: #fff;
    font-weight: 800;
    margin-top: 8px;
}

.footer-bottom {
    display: flex;
    justify-content: space-between;
    gap: 14px;
    width: min(1220px, calc(100% - 40px));
    margin: 26px auto 0;
    border-top: 1px solid rgba(255, 255, 255, 0.18);
    padding-top: 18px;
}

.content-section,
.hero-section {
    animation: sectionIn 420ms ease both;
}

@keyframes sectionIn {
    from {
        opacity: 0;
        transform: translateY(10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

@media (prefers-reduced-motion: reduce) {
    *,
    *::before,
    *::after {
        scroll-behavior: auto !important;
        animation-duration: 0.01ms !important;
        animation-iteration-count: 1 !important;
        transition-duration: 0.01ms !important;
    }
}

@media (max-width: 1040px) {
    .hero-section,
    .post-page-grid {
        grid-template-columns: 1fr;
    }

    .hero-media {
        min-height: 330px;
    }

    .project-grid,
    .admission-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .instagram-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .related-panel {
        position: static;
    }
}

@media (max-width: 780px) {
    .top-strip,
    .brand-row,
    .main-nav,
    .portal-main {
        width: min(100% - 24px, 1220px);
    }

    .brand-row {
        grid-template-columns: 1fr;
        gap: 12px;
    }

    .portal-search {
        flex-direction: column;
    }

    .portal-search button {
        width: 100%;
    }

    .hero-copy {
        padding: 24px 20px;
    }

    .about-grid,
    .contact-grid,
    .project-grid,
    .gallery-grid,
    .instagram-grid,
    .admission-grid {
        grid-template-columns: 1fr;
    }

    .gallery-card,
    .gallery-card:nth-child(1),
    .gallery-card:nth-child(4),
    .gallery-card:nth-child(5),
    .gallery-card:nth-child(6),
    .gallery-card.cms-gallery-card {
        grid-column: auto;
        min-height: 240px;
    }

    .archive-news-item {
        grid-template-columns: 96px minmax(0, 1fr);
    }

    .footer-grid,
    .footer-bottom {
        grid-template-columns: 1fr;
        flex-direction: column;
    }
}

@media (max-width: 520px) {
    .top-strip {
        flex-direction: column;
        gap: 4px;
    }

    .school-brand {
        align-items: flex-start;
    }

    .brand-logo {
        width: 62px;
        height: 62px;
    }

    .hero-copy h1 {
        font-size: 2rem;
        line-height: 1.04;
    }

    .hero-actions {
        display: grid;
    }

    .primary-action,
    .secondary-action {
        width: 100%;
    }

    .main-nav {
        justify-content: flex-start;
        gap: 2px;
    }

    .main-nav a,
    .nav-alert-button {
        font-size: 0.84rem;
        padding: 9px 7px;
    }

    .weather-alert-actions {
        display: grid;
    }

    .legacy-weather-frame {
        height: 900px;
    }

    .archive-news-item {
        grid-template-columns: 1fr;
    }

    .archive-thumb {
        aspect-ratio: 16 / 9;
    }
}
"""
    js = """document.querySelectorAll(".instagram-post-media .instagram-card-embed").forEach((embed) => {
    const instagramUrl = embed.dataset.instgrmPermalink || embed.querySelector("a")?.href;
    const shortcode = instagramUrl?.match(/\\/(?:p|reel|tv)\\/([^/?#]+)/i)?.[1];
    if (!instagramUrl || !shortcode) {
        return;
    }

    const media = embed.closest(".instagram-post-media");
    const card = embed.closest(".instagram-post-card");
    const title = card?.querySelector(".instagram-post-body h3")?.textContent?.trim() || "Publicação da EE São José";
    const date = card?.querySelector(".news-meta span")?.textContent?.trim() || "";
    const preview = document.createElement("a");
    const image = document.createElement("img");
    const caption = document.createElement("span");
    const label = document.createElement("strong");
    const detail = document.createElement("small");

    preview.className = "instagram-local-preview";
    preview.href = instagramUrl;
    preview.target = "_blank";
    preview.rel = "noopener";
    preview.setAttribute("aria-label", `${title} — abrir no Instagram`);

    image.src = `/assets/img/instagram-${shortcode}.jpg`;
    image.alt = title;
    image.loading = "lazy";
    image.addEventListener("error", () => preview.classList.add("is-fallback"), { once: true });

    label.textContent = "Ver no Instagram";
    detail.textContent = date || "@eesjms";
    caption.append(label, detail);
    preview.append(image, caption);
    media?.classList.add("has-local-preview");
    embed.replaceWith(preview);
});

const searchInputs = Array.from(document.querySelectorAll("[data-search]"));
const forms = Array.from(document.querySelectorAll("[data-search-form]"));
const posts = Array.from(document.querySelectorAll("[data-post]"));
const groups = Array.from(document.querySelectorAll("[data-date-group]"));
const emptyState = document.querySelector("[data-empty-state]");

const normalize = (value) =>
    value
        .normalize("NFD")
        .replace(/[\\u0300-\\u036f]/g, "")
        .toLowerCase()
        .trim();

const applySearch = (value) => {
    const query = normalize(value);
    let visible = 0;

    posts.forEach((post) => {
        const text = normalize(post.dataset.searchText || "");
        const match = !query || text.includes(query);
        post.hidden = !match;
        if (match) {
            visible += 1;
        }
    });

    groups.forEach((group) => {
        const visiblePost = Array.from(group.querySelectorAll("[data-post]")).some((post) => !post.hidden);
        group.hidden = !visiblePost;
    });

    if (emptyState) {
        emptyState.hidden = visible !== 0;
    }
};

searchInputs.forEach((input) => {
    input.addEventListener("input", () => {
        searchInputs.forEach((otherInput) => {
            if (otherInput !== input) {
                otherInput.value = input.value;
            }
        });
        applySearch(input.value);
    });
});

forms.forEach((form) => {
    form.addEventListener("submit", (event) => {
        event.preventDefault();
        applySearch(form.querySelector("[data-search]")?.value || "");
        document.querySelector("#arquivo")?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
});

window.addEventListener("load", () => {
    if (window.instgrm?.Embeds?.process) {
        window.instgrm.Embeds.process();
    }
});
"""
    style_path = project_dir / "assets" / "css" / "style-20260619.css"
    script_path = project_dir / "assets" / "js" / "script-20260619.js"
    style_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    if not style_path.exists():
        style_path.write_text(css, encoding="utf-8")
    if not script_path.exists():
        script_path.write_text(js, encoding="utf-8")


def import_takeout(zip_path: Path, project_dir: Path) -> None:
    assets_dir = project_dir / "assets" / "img"
    with zipfile.ZipFile(zip_path) as zf:
        feed_entry = find_feed(zf)
        feed_xml = zf.read(feed_entry).decode("utf-8-sig")
        image_map = extract_images(zf, assets_dir)

    blog_title, posts, missing_images = build_posts(feed_xml, image_map)
    if not posts:
        raise RuntimeError("Nenhuma postagem publicada foi encontrada no feed.")
    events = load_events(project_dir)

    write_portal_assets(project_dir)
    write_portal_index(project_dir, blog_title, posts, events)
    write_portal_post_pages(project_dir, blog_title, posts)
    write_weather_station_page(project_dir, blog_title)

    print(f"Blog: {blog_title}")
    print(f"Postagens importadas: {len(posts)}")
    print(f"Eventos cadastrados: {len(events)}")
    print(f"Imagens extraídas: {len(image_map)}")
    print(f"Referências de imagem sem arquivo local: {missing_images}")
    print(f"Página inicial: {project_dir / 'index.html'}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Importa um backup Google Takeout do Blogger para site estático.")
    parser.add_argument("zip_path", type=Path, help="Caminho do arquivo .zip do Takeout")
    parser.add_argument("--project-dir", type=Path, default=Path.cwd(), help="Pasta raiz do site")
    args = parser.parse_args()

    import_takeout(args.zip_path, args.project_dir.resolve())


if __name__ == "__main__":
    main()
